name: CI HTML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Lister les fichiers
        run: ls -la

      - name: Installer tidy (validateur HTML)
        run: sudo apt-get update && sudo apt-get install tidy -y

      - name: Vérifier le fichier HTML
        run: tidy -errors -q index.html || true
